### ISSUE TITLE
ListenBrainz scrobbling

### ISSUE THREAD

**Issue by Martysh12** [jplexer/BarterBird#4]
Add support for scrobbling to ListenBrainz.

See [the API documentation](https://listenbrainz.readthedocs.io/en/latest/users/api/index.html) for more info on adding ListenBrainz support.

**Comment by Martysh12** [comment]
P.S, it has a [last.fm-compatible API too.](https://listenbrainz.readthedocs.io/en/latest/users/api-compat.html)

**Comment by jplexer** [comment]
Added in 1a51a8677fe8ab6047579bb5c1408d7d4e86ba91
